//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE_COMMANDE
    {
        public System.Guid factureCommandeId { get; set; }
        public Nullable<System.Guid> factureId { get; set; }
        public Nullable<System.Guid> commandeId { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
        public virtual FACTURE FACTURE { get; set; }
    }
}
